# Generated by Django 4.1 on 2022-08-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("blogs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="categories.category"),
        ),
    ]
