# Generated by Django 4.1 on 2022-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(default="None", max_length=280),
        ),
    ]
